#!/bin/bash


PYTHON=python

if [[ -n "$(which python3 2>&-)" ]]; then
  PYTHON=python3
fi

if [[ $EUID -ne 0 ]]; then
  echo "imgbase must be run as root!"
  exit 1
fi

$PYTHON -m imgbased.__main__ $@
