#!/usr/bin/bash

TYPE=${1:-rootfs}
NAME=${2:-"<ProductName>"}
VENDOR=${3:-"<com.example.vendor>"}
ARCH=${4:-"x86_64"}
VERSION=${5:-$(date +%Y%m%d)}
EXTRA_RELEASE=${6}

if [[ -n $@ ]];
then
echo $TYPE:$NAME:$VENDOR:$ARCH:$VERSION
else
echo "Usage: $0 TYPE NAME VENDOR [ARCH] [VERSION] [EXTRA_RELEASE]"
fi
