.\" Manpage for imgbase-copy-bootfiles.
.\" Contact rbarry@redhat.com to correct errors or typos.
.TH man 8 "9 January 2018" "1.0" "imgbase-fix-new-kernel man page"
.SH NAME
imgbase-fix-new-kernel \- clean up after the behavior of new-kernel-pkg
.SH SYNOPSIS
imgbase-fix-new-kernel
.SH DESCRIPTION
imgbase-newfix-new-kernel will examine the current configuration of grub2
and find any discrepancies which would result in the hypervisor failing to
boot.
.SH COPYRIGHT
Copyright (C) 2018, Red Hat, Inc.
