IMGBASED_TMPFILE_PREFIX = "tmp.imgbased."

IMGBASED_MODE_INIT = "init"
IMGBASED_MODE_UPDATE = "update"
IMGBASED_MODES = (IMGBASED_MODE_INIT, IMGBASED_MODE_UPDATE)

IMGBASED_STATE_DIR = "/var/imgbased"
IMGBASED_IMAGE_UPDATED = IMGBASED_STATE_DIR + "/.image-updated"

IMGBASED_PERSIST_PATH = IMGBASED_STATE_DIR + "/persisted-rpms/"
