---
name: CI

# TODO:
# The automation we had in Jenkins did deep integration testing
# using virtualization.
# We should do something similar here.

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: almalinux-9
            shortcut: el9
            container-name: almalinux9
          - name: almalinux-10
            shortcut: el10
            container-name: almalinux10
          - name: centos-stream-9
            shortcut: el9s
            container-name: el9stream
          - name: centos-stream-10
            shortcut: el10s
            container-name: el10stream

    name: ${{ matrix.name }}

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
      - name: Checkout sources
        uses: ovirt/checkout-action@main

      - name: Mark repository as safe
        run: git config --global --add safe.directory "$(pwd)"

      - name: Install tools that should be in buildcontainer / BuildRequires
        run: dnf install -y asciidoc python3-pip

      - name: Install Python tools
        run: pip install pycodestyle pyflakes coverage systemd pytest pytest-mock

      - name: Autogen
        run: ./autogen.sh

      - name: Check code
        run: make -j distcheck

      - name: Build RPM
        run: make rpm

      - name: Collect artifacts
        run: |
          mkdir -p exported-artifacts
          find ~/rpmbuild/*RPMS/ -iname \*rpm -exec mv "{}" $ARTIFACTS_DIR/ \;
          mv ./*tar.xz $ARTIFACTS_DIR/

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: rpm-${{ matrix.shortcut }}
          path: ${{ env.ARTIFACTS_DIR }}

  publish-rpms:
    permissions:
      artifact-metadata: read
    needs: build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ovirt/ovirt-workflows/.github/workflows/publish-rpms.yml@main
    secrets: inherit
